import { useMemo, useState } from "react";
import { api } from "./api";
import { useBackend } from "./useBackend";
import type { Beacon, Decision, Incident, Scenario, State, Telemetry, Vehicle } from "./types";

const telemetryGroups = [
  ["FORWARD PERCEPTION", ["forward_lidar_cm", "rate_of_closure_mps", "thermal_temp_gradient", "human_detection_conf", "visual_fog_density_pct"]],
  ["CLIFF & ROAD BOUNDARY SAFETY", ["left_cliff_dist_cm", "right_cliff_dist_cm", "ground_loss_trigger", "pitch_angle_degrees", "roll_angle_degrees"]],
  ["PROPULSION & VEHICLE DIAGNOSTICS", ["vehicle_velocity_kph", "motor_current_draw_ma", "core_temp_celsius", "batt_voltage_millivolts", "braking_pressure_psi", "runtime_seconds"]],
  ["WIRELESS V2I", ["active_beacon_id", "beacon_rssi_dbm", "curve_speed_limit_kph", "hazard_warning_flag", "local_gps_lat_offset", "local_gps_lon_offset"]],
] as const;
const scenarios: Scenario[] = ["NORMAL", "DENSE_FOG", "OBSTACLE", "CLIFF_EDGE", "V2I_HAZARD", "SENSOR_FAILURE", "BEACON_FAILURE"];
const severityClass = (value?: string) => (value ?? "NORMAL").toLowerCase();
const format = (value: unknown) => typeof value === "number" ? Number.isInteger(value) ? String(value) : value.toFixed(2) : String(value ?? "—");

function status(state: State | null, incidents: Incident[]) { const critical = incidents.find((item) => item.status !== "resolved" && item.severity === "CRITICAL"); if (critical) return { label: `CRITICAL: ${critical.vehicle_id} ${critical.hazard_type.replaceAll("_", " ")}`, tone: "critical" }; if (state?.scenario === "DENSE_FOG") return { label: "WARNING: LOW VISIBILITY", tone: "warning" }; const offline = state?.beacons.find((item) => item.communication_state === "unavailable"); if (offline) return { label: `BEACON ${offline.beacon_id} OFFLINE`, tone: "warning" }; return { label: "ALL SYSTEMS OPERATIONAL", tone: "normal" }; }

function Map({ state, onSelect }: { state: State; onSelect: (id: string) => void }) {
  const project = (point: { x_m: number; y_m: number }) => ({ x: 55 + (point.x_m + 150) * 0.78, y: 470 - (point.y_m + 200) * 0.62 });
  const decision = (vehicle: Vehicle) => state.safety_decisions.find((item) => item.vehicle_id === vehicle.vehicle_id);
  return <section className="panel map-panel"><header><h2>LIVE DIGITAL TWIN</h2><span>FICTIONAL LOCAL COORDINATES · SIMULATED</span></header><svg viewBox="0 0 800 500" role="img" aria-label="Virtual mine map">
    <rect width="800" height="500" className="map-bg" />
    {state.topology.safe_zones.map((zone) => <polygon key={zone.zone_id} points={zone.boundary.map((point) => { const p = project(point); return `${p.x},${p.y}`; }).join(" ")} className="safe-zone" />)}
    {state.topology.cliff_boundaries.map((cliff) => { const a = project(cliff.start), b = project(cliff.end); return <line key={cliff.boundary_id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="cliff" />; })}
    {state.topology.road_segments.map((road) => { const a = project(road.start), b = project(road.end); return <line key={road.segment_id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="road" />; })}
    {state.beacons.map((beacon) => { const p = project(beacon.position); return <g key={beacon.beacon_id} className={`beacon ${beacon.communication_state}`}><rect x={p.x - 7} y={p.y - 7} width="14" height="14"/><text x={p.x + 11} y={p.y - 10}>{beacon.beacon_id}</text><text x={p.x + 11} y={p.y + 5}>{beacon.speed_limit_kph} km/h</text></g>; })}
    {state.vehicles.map((vehicle) => { const p = project(vehicle.position), safety = decision(vehicle); return <g role="button" tabIndex={0} onClick={() => onSelect(vehicle.vehicle_id)} onKeyDown={(event) => event.key === "Enter" && onSelect(vehicle.vehicle_id)} key={vehicle.vehicle_id} className={`truck ${severityClass(safety?.severity)}`}><circle cx={p.x} cy={p.y} r="13"/><text x={p.x} y={p.y + 4}>{vehicle.vehicle_id}</text><text x={p.x + 17} y={p.y + 17}>{format(vehicle.velocity_kph)} km/h · {safety?.severity ?? "NORMAL"}</text></g>; })}
  </svg><footer><i className="legend normal"/> Normal <i className="legend warning"/> Warning <i className="legend critical"/> Critical <i className="legend beacon"/> V2I Beacon</footer></section>;
}

function TelemetryPanel({ telemetry, vehicleId }: { telemetry: Telemetry | null; vehicleId: string }) { return <section className="panel telemetry"><header><h2>{vehicleId} · TELEMETRY22</h2><span>SIMULATED SENSOR FUSION</span></header>{telemetry ? telemetryGroups.map(([title, fields]) => <div key={title} className="telemetry-group"><h3>{title}</h3>{fields.map((field) => <div className="metric" key={field}><code>{field}</code><b>{format(telemetry[field])}</b></div>)}</div>) : <p>Awaiting backend telemetry…</p>}</section>; }

function Incidents({ incidents, refresh }: { incidents: Incident[]; refresh: () => Promise<void> }) { return <section className="panel incidents"><header><h2>LIVE INCIDENTS</h2><span>{incidents.filter((item) => item.status !== "resolved").length} ACTIVE</span></header>{incidents.length === 0 ? <p className="empty">No recorded incidents.</p> : incidents.slice().reverse().map((incident) => <article key={incident.incident_id} className={`incident ${severityClass(incident.severity)}`}><div><strong>{incident.severity}</strong><span>{incident.incident_id} · {incident.vehicle_id} · t+{format(incident.timestamp_seconds)}s</span></div><h3>{incident.hazard_type.replaceAll("_", " ")}</h3><p>{incident.message}</p><small>{incident.safety_action} · {incident.status}</small>{incident.status === "open" && <button onClick={async () => { await api.acknowledge(incident.incident_id); await refresh(); }}>ACKNOWLEDGE</button>}</article>)}</section>; }

function BeaconControls({ beacons, refresh }: { beacons: Beacon[]; refresh: () => Promise<void> }) { const [messages, setMessages] = useState<Record<string, string>>({}); return <section className="panel beacons"><header><h2>V2I BEACON CONTROL</h2><span>SIMULATED ESP-NOW</span></header>{beacons.map((beacon) => <article key={beacon.beacon_id} className="beacon-row"><div><b>{beacon.beacon_id}</b><span className={beacon.communication_state}>{beacon.communication_state}</span><small>{beacon.hazard_broadcast_active ? beacon.hazard_message : "No active hazard"}</small></div><label>Speed limit <input aria-label={`${beacon.beacon_id} speed limit`} type="number" value={beacon.speed_limit_kph} onChange={async (event) => { await api.speedLimit(beacon.beacon_id, Number(event.target.value)); await refresh(); }} /> km/h</label><div className="hazard-control"><input aria-label={`${beacon.beacon_id} hazard message`} placeholder="Hazard message" value={messages[beacon.beacon_id] ?? ""} onChange={(event) => setMessages({ ...messages, [beacon.beacon_id]: event.target.value })}/><button onClick={async () => { await api.injectHazard(beacon.beacon_id, messages[beacon.beacon_id] || "Simulated hazard"); await refresh(); }}>INJECT</button>{beacon.hazard_broadcast_active && <button className="subtle" onClick={async () => { await api.clearHazard(beacon.beacon_id); await refresh(); }}>CLEAR</button>}</div></article>)}</section>; }

function Hud({ vehicle, telemetry, decision, connected }: { vehicle: Vehicle; telemetry: Telemetry | null; decision?: Decision; connected: boolean }) { const critical = decision?.severity === "CRITICAL"; return <section className={`hud ${critical ? "hud-critical" : ""}`}><div className="hud-title">THIRD EYE <span>SIMULATION MODE</span></div><div className="hud-truck">{vehicle.vehicle_id}</div>{critical ? <><div className="hud-alert">CRITICAL<br/><b>{decision.hazard_type?.replaceAll("_", " ")}</b></div><div className="hud-distance">{format(telemetry?.forward_lidar_cm)} cm</div><div className="brake">EMERGENCY BRAKING<br/>SIMULATED ACTIVE</div></> : <><div className="hud-speed">{format(vehicle.velocity_kph)} <small>km/h</small></div><div className="hud-grid"><span>LIMIT <b>{format(telemetry?.curve_speed_limit_kph)} km/h</b></span><span>BEACON <b>{format(telemetry?.active_beacon_id)}</b></span><span>OBSTACLE <b>{format(telemetry?.forward_lidar_cm)} cm</b></span><span>FOG <b>{format(telemetry?.visual_fog_density_pct)}%</b></span></div><div className={`hud-status ${severityClass(decision?.severity)}`}>{connected ? `SYSTEM ${decision?.severity ?? "NORMAL"}` : "BACKEND DISCONNECTED"}</div></>}</section>; }

export function App() { const { state, incidents, telemetry, selectedVehicle, setSelectedVehicle, connected, refresh } = useBackend(); const [hud, setHud] = useState(false); const current = state?.vehicles.find((item) => item.vehicle_id === selectedVehicle); const currentDecision = state?.safety_decisions.find((item) => item.vehicle_id === selectedVehicle); const banner = status(state, incidents); const fog = Number(telemetry?.visual_fog_density_pct ?? 0); const activeCritical = incidents.filter((item) => item.status !== "resolved" && item.severity === "CRITICAL").length;
  if (!state || !current) return <main className="loading"><h1>THIRD EYE</h1><p>{connected ? "Loading simulated mine state…" : "BACKEND DISCONNECTED — retrying connection"}</p></main>;
  if (hud) return <main className="hud-page"><button className="back" onClick={() => setHud(false)}>← CONTROL ROOM</button><Hud vehicle={current} telemetry={telemetry} decision={currentDecision} connected={connected}/></main>;
  return <main><header className="topbar"><div><h1>THIRD EYE</h1><p>Mining Safety & Fleet Monitoring System</p></div><div className={`system-banner ${connected ? banner.tone : "critical"}`}><b>{connected ? banner.label : "BACKEND DISCONNECTED"}</b><span>SIMULATION MODE · t+{format(state.clock.elapsed_seconds)}s</span></div><button onClick={() => setHud(true)}>DRIVER HUD</button></header><section className="kpis"><Kpi label="ACTIVE DUMPERS" value={`${state.vehicles.length} / ${state.vehicles.length}`} note="Virtual fleet online"/><Kpi label="ACTIVE BEACONS" value={`${state.beacons.filter((item) => item.communication_state === "available").length} / ${state.beacons.length}`} note="Simulated V2I nodes"/><Kpi label="VISIBILITY" value={`${Math.max(50, Math.round(1000 * (1 - fog / 100)))} m`} note="Derived from simulated fog"/><Kpi label="FOG DENSITY" value={`${format(fog)}%`} note="Camera context"/><Kpi label="SYSTEM TEMP" value={`${format(telemetry?.core_temp_celsius)} °C`} note="Simulated edge compute"/><Kpi label="HUMIDITY" value="NOT AVAILABLE" note="NOT SPECIFIED IN PROPOSAL"/><Kpi label="SHIFT SAFETY SCORE" value="NOT AVAILABLE" note="NOT SPECIFIED IN PROPOSAL"/><Kpi label="ACTIVE CRITICAL" value={String(activeCritical)} note="Backend incident state" critical={activeCritical > 0}/></section><section className="dashboard-grid"><Map state={state} onSelect={setSelectedVehicle}/><section className="panel controls"><header><h2>SIMULATION CONTROL</h2><span>{state.clock.status}</span></header><div><button onClick={async () => { await api.start(); await refresh(); }}>START</button><button onClick={async () => { await api.pause(); await refresh(); }}>PAUSE</button><button className="subtle" onClick={async () => { await api.reset(); await refresh(); }}>RESET</button></div><label>Scenario<select value={state.scenario} onChange={async (event) => { await api.scenario(event.target.value as Scenario); await refresh(); }}>{scenarios.map((scenario) => <option key={scenario}>{scenario}</option>)}</select></label><p>All controls operate on the authoritative software simulation.</p></section><TelemetryPanel telemetry={telemetry} vehicleId={selectedVehicle}/><Incidents incidents={incidents} refresh={refresh}/><BeaconControls beacons={state.beacons} refresh={refresh}/><section className="panel environment"><header><h2>ENVIRONMENT</h2><span>SIMULATED</span></header><p><b>Visibility</b><span>{Math.max(50, Math.round(1000 * (1 - fog / 100)))} m</span></p><p><b>Fog density</b><span>{format(fog)}%</span></p><p><b>Temperature</b><span>{format(telemetry?.core_temp_celsius)} °C edge compute</span></p><p><b>Humidity</b><span>NOT AVAILABLE</span></p></section></section></main>;
}
function Kpi({ label, value, note, critical = false }: { label: string; value: string; note: string; critical?: boolean }) { return <article className={`kpi ${critical ? "critical" : ""}`}><span>{label}</span><b>{value}</b><small>{note}</small></article>; }
